source 'https://github.com/splinesoft/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '17.0'

project 'Mudrammer'

plugin 'cocoapods-keys', {
  :project => "Mudrammer",
  :keys => [
    "HOCKEYBETA_KEY",
    "HOCKEYLIVE_KEY",
    "SPLINESOFT_AFFILIATE_KEY",
    "USERVOICE_FORUM_SITE",
    "USERVOICE_FORUM_ID",
  ]
}

target 'MUDRammer' do
  pod 'libextobjc', '0.6'
  pod 'BlocksKit', '~> 2.2'

  # Splinesoft
  pod 'SPLCore', :path => '/Users/bob/code/SPLCore'
  pod 'SSAccessibility', '0.2.0'
  pod 'SSDataSources', '0.8.5'
  pod 'SSOperations', '0.1.0'
  pod 'SSApplication', '0.3.0'
  pod 'SPLUserActivity', '0.1.2'

  # Networking  
  pod 'CocoaAsyncSocket', '7.3.5'
  # pod 'libtelnet', '0.21'

  # Engine
  pod 'SAMRateLimit', '0.2.0'
  pod 'KVOController', '1.0.3'
  pod 'OSCache', '1.2'
  pod 'MyLilTimer', '0.1.0'

  # Analytics
  # pod 'ARAnalytics/HockeyApp', '3.6.2' # Removed - HockeyApp shut down in 2019

  # UI
  pod 'TOWebViewController', '2.0.17'
  pod 'DAKeyboardControl', '2.4.0'
  pod 'TTTAttributedLabel', '1.13.1'
  pod 'JASidePanels', '1.3.2'
  pod 'Masonry', '0.6.2'
  pod 'JSQSystemSoundPlayer', '4.0.0'
  pod 'JTSImageViewController', '1.4'
  pod 'IFTTTLaunchImage', '0.4.1'
  pod 'SwiftGen', '~> 6.0'

  # Support
  pod 'uservoice-iphone-sdk', '3.2.3'

  # Forms
  pod 'QuickDialog', :subspecs => ['Core', 'Extras'], :git => 'https://github.com/escoz/QuickDialog.git', :commit => 'c5891e6d63def55af5b7f5f5efe8d64330d3a4fd'
  pod 'FXForms', '1.2.13'

  # Pods Ack.
  pod 'VTAcknowledgementsViewController', '0.14'

  target "MRTests" do
    inherit! :search_paths
    pod 'MagicalRecord'
    pod 'Expecta'
    pod 'OCMock'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      # Suppress newline-eof warning for pods (especially deprecated BlocksKit)
      config.build_settings['WARNING_CFLAGS'] ||= '$(inherited)'
      config.build_settings['WARNING_CFLAGS'] += ' -Wno-newline-eof'
    end
  end

  # Add libtelnet header and library paths to Pods target
  installer.pods_project.targets.each do |target|
    if target.name == 'Pods-MUDRammer'
      target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        config.build_settings['HEADER_SEARCH_PATHS'] << '/Users/bob/code/libtelnet '

        # Use Xcode build settings to conditionally set library paths
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]'] = '$(inherited) /Users/bob/code/libtelnet/build-sim/Release-iphonesimulator'
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphoneos*]'] = '$(inherited) /Users/bob/code/libtelnet/build-ipados/Debug'

        config.build_settings['OTHER_LDFLAGS[sdk=iphonesimulator*]'] = '$(inherited) /Users/bob/code/libtelnet/build-sim/Release-iphonesimulator/liblibtelnet.a'
        config.build_settings['OTHER_LDFLAGS[sdk=iphoneos*]'] = '$(inherited) /Users/bob/code/libtelnet/build-ipados/Debug/liblibtelnet.a'
      end
    end
  end

  # Add libtelnet header and library paths to main app target
  project_path = installer.aggregate_targets[0].user_project_path
  project = Xcodeproj::Project.open(project_path)
  project.targets.each do |target|
    if target.name == 'MUDRammer'
      target.build_configurations.each do |config|
        # Clean up any existing libtelnet paths from HEADER_SEARCH_PATHS
        if config.build_settings['HEADER_SEARCH_PATHS'].is_a?(Array)
          config.build_settings['HEADER_SEARCH_PATHS'].reject! { |path| path.to_s.include?('libtelnet') }
        elsif config.build_settings['HEADER_SEARCH_PATHS'].is_a?(String)
          paths = config.build_settings['HEADER_SEARCH_PATHS'].split(' ')
          paths.reject! { |path| path.include?('libtelnet') }
          config.build_settings['HEADER_SEARCH_PATHS'] = paths.join(' ')
        end
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        config.build_settings['HEADER_SEARCH_PATHS'] << '/Users/bob/code/libtelnet '

        # Clean up any existing libtelnet paths from LIBRARY_SEARCH_PATHS
        if config.build_settings['LIBRARY_SEARCH_PATHS'].is_a?(Array)
          config.build_settings['LIBRARY_SEARCH_PATHS'].reject! { |path| path.to_s.include?('libtelnet') }
        elsif config.build_settings['LIBRARY_SEARCH_PATHS'].is_a?(String)
          paths = config.build_settings['LIBRARY_SEARCH_PATHS'].split(' ')
          paths.reject! { |path| path.include?('libtelnet') }
          config.build_settings['LIBRARY_SEARCH_PATHS'] = paths.join(' ')
        end

        # Clean up any existing libtelnet references from OTHER_LDFLAGS
        if config.build_settings['OTHER_LDFLAGS'].is_a?(Array)
          config.build_settings['OTHER_LDFLAGS'].reject! { |flag| flag.to_s.include?('libtelnet') }
        elsif config.build_settings['OTHER_LDFLAGS'].is_a?(String)
          flags = config.build_settings['OTHER_LDFLAGS'].split(' ')
          flags.reject! { |flag| flag.include?('libtelnet') }
          config.build_settings['OTHER_LDFLAGS'] = flags.join(' ')
        end

        # Use Xcode build settings to conditionally set library paths
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*]'] = '$(inherited) /Users/bob/code/libtelnet/build-sim/Release-iphonesimulator'
        config.build_settings['LIBRARY_SEARCH_PATHS[sdk=iphoneos*]'] = '$(inherited) /Users/bob/code/libtelnet/build-ipados/Debug'

        config.build_settings['OTHER_LDFLAGS[sdk=iphonesimulator*]'] = '$(inherited) /Users/bob/code/libtelnet/build-sim/Release-iphonesimulator/liblibtelnet.a'
        config.build_settings['OTHER_LDFLAGS[sdk=iphoneos*]'] = '$(inherited) /Users/bob/code/libtelnet/build-ipados/Debug/liblibtelnet.a'
      end
    end
  end
  project.save
end
